### ISSUE TITLE
DayPicker 最小日期出現00

### ISSUE THREAD

**Issue by ChengTaHuang** [ycuwq/DatePicker#11]
![error](https://i.imgur.com/qqvyya7.jpg)

發現是DayPicker在init的時候執行updateDay(),拿到的mMinday沒有初始值，所以為0,導致若該月只有30日還是會拿到31長度的datalist

目前方法是mDatePicker.onMonthSelected(calendar.get(Calendar.MONTH));
去第二次更新日期，就會讓mMinday為1

**Comment by ycuwq** [comment]
已经修复了，更新版本到1.2.2即可。感谢反馈(๑•̀ㅂ•́)و✧
