### ISSUE TITLE
Question : Is it possible to change the date format ?

### ISSUE THREAD

**Issue by ManuEpi** [ycuwq/DatePicker#17]
Hello , nice library but I wonder if we can change date format from (YY-mm-dd) TO (dd-mm-YY) ?

Thanks

**Comment by ManuEpi** [comment]
I didn't see any parameters so I downloaded your library and I just modified layout_date.xml in order to have DAY_MONTH_YEAR selection.

Thanks

**Comment by JonathanNet** [comment]
Did you find any solutions?

**Comment by ycuwq** [comment]
Update to 1.3.4, you can use custom DatePicker, see [demo](https://github.com/ycuwq/DatePicker/blob/master/sample/src/main/java/com/ycuwq/datepicker/sample/CustomDatePicker.java)
