### ISSUE TITLE
设置字体30sp，月份滑到12月，日选择出现bug

### ISSUE THREAD

**Issue by YinJazz** [ycuwq/DatePicker#18]
设置字体30sp，月份滑到12月，日选择出现bug

**Comment by ycuwq** [comment]
感谢您的反馈，不过能否详细说明问题和机型，我这里没有复现。

**Comment by zmlim** [comment]
Hi, how do you use the method 
  datePickerDialogFragment.setOnDateChooseListener();

**Comment by ycuwq** [comment]
> Hi, how do you use the method
> datePickerDialogFragment.setOnDateChooseListener();

```
DatePickerDialogFragment datePickerDialogFragment = new DatePickerDialogFragment();
datePickerDialogFragment.setOnDateChooseListener(new DatePickerDialogFragment.OnDateChooseListener() {
	@Override
	public void onDateChoose(int year, int month, int day) {
		Toast.makeText(getApplicationContext(), year + "-" + month + "-" + day, Toast.LENGTH_SHORT).show();
	}
});
datePickerDialogFragment.show(getSupportFragmentManager(), "DatePickerDialogFragment");
```

**Comment by zmlim** [comment]
> > Hi, how do you use the method
> > datePickerDialogFragment.setOnDateChooseListener();
> 
> ```
> DatePickerDialogFragment datePickerDialogFragment = new DatePickerDialogFragment();
> datePickerDialogFragment.setOnDateChooseListener(new DatePickerDialogFragment.OnDateChooseListener() {
> 	@Override
> 	public void onDateChoose(int year, int month, int day) {
> 		Toast.makeText(getApplicationContext(), year + "-" + month + "-" + day, Toast.LENGTH_SHORT).show();
> 	}
> });
> datePickerDialogFragment.show(getSupportFragmentManager(), "DatePickerDialogFragment");
> ```

Thank you for the prompt reply! Really appreciate it!

**Comment by YinJazz** [comment]
I used it on activity!

<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

<com.ycuwq.datepicker.date.DatePicker
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:dateTextSize="30sp"
        app:dateSelectedTextSize="30sp"/>


</android.support.constraint.ConstraintLayout>

avd used tablet

**Comment by ycuwq** [comment]
> I used it on activity!
> 
> <android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
> xmlns:app="http://schemas.android.com/apk/res-auto"
> xmlns:tools="http://schemas.android.com/tools"
> android:layout_width="match_parent"
> android:layout_height="match_parent"
> tools:context=".MainActivity">
> 
> <com.ycuwq.datepicker.date.DatePicker
> android:layout_width="match_parent"
> android:layout_height="wrap_content"
> app:dateTextSize="30sp"
> app:dateSelectedTextSize="30sp"/>
> 
> </android.support.constraint.ConstraintLayout>
> 
> avd used tablet

I tried it on Pixel C API 28, and it works fine.
Can you describe the problem in more detail?

**Comment by YinJazz** [comment]
Activity do  setContentView(R.layout.activity_main) onley.
activity_main.xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.ycuwq.datepicker.date.DatePicker
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:dateTextSize="30sp"
        app:dateSelectedTextSize="30sp"/>


</android.support.constraint.ConstraintLayout>

avd use nexus 7 api 28
月份滑到12，日的高度会比年月的高

**Comment by ycuwq** [comment]
还是没有复现，如果你有兴趣的话，可以提交一个Pull request。我这边环境都用的一样，没有复现出来
