### ISSUE TITLE
手动调用datepicker.setDate(year,month,day-1);会显示到空白，smoothScroll设置false滑到最后一个后会报错

### ISSUE THREAD

**Issue by pomforandroid** [ycuwq/DatePicker#3]
不停地加一加一，报java.lang.IndexOutOfBoundsException: Index: 30, Size: 30

**Comment by ycuwq** [comment]
第一个问题我已经复现出了,后续会处理这个问题.
`setDate(year, month, day, false)`这个的问题我并没有复现出来,你能在详细的说说么?

**Comment by pomforandroid** [comment]
比如说一个月只有30天的话，你设置了day是31天，false，就会报IndexOutOfBoundsException

**Comment by ycuwq** [comment]
已经修复完成，你更新到1.0.9再试一下。
