### ISSUE TITLE
发现了两个问题

### ISSUE THREAD

**Issue by cjh94520** [ycuwq/DatePicker#4]
版本是最新的：1.0.9

在DatePicker控件xml布局设置了
1.selectedTextColor 颜色设置无效，还是蓝色
2.设置字体大小后，Day控件位置错位了

可否解决下？可联系我Q：892546937

**Comment by ycuwq** [comment]
已经修复，更新到1.1.0后再试一下。
感谢你对我这个项目的支持与帮助(*^_^*)。
