### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [ycuwq/DatePicker#6]
Hi @ycuwq  I am a graphic designer and i noticed that your good project doesn't have a logo yet. I would like to contribute by designing one here for free. I just need first your permission before i begin my design.
Thanks and my best regards! 

- Tobaloidee

**Comment by ycuwq** [comment]
Thank you. But this project is too simple and it is not worth spending your time.

**Comment by Tobaloidee** [comment]
It is totally fine with me..it will also improve my portfolio..I just want to contribute Sir.. :)

**Comment by ycuwq** [comment]
Ok ,  Thank you.

**Comment by Tobaloidee** [comment]
will show you here when i am done..

**Comment by Tobaloidee** [comment]
Here Sir, i hope you like it! will make a PR if you do..pls let me know..

![datepicker-02](https://user-images.githubusercontent.com/36028424/42072309-62a2f29c-7b92-11e8-960d-2bef514f98fe.png)

**Comment by ycuwq** [comment]
Looks great.I think it would be better to change ‘00’ to ‘30’.
Logotypes,I like the first one.
Thank you for your logos and nice job.

**Comment by Tobaloidee** [comment]
Sure Sir, ill edit and make a PR after for the file upload and update the readme with it..

**Comment by Tobaloidee** [comment]
here's the PR #7 with the new logo Sir..

![logotype](https://user-images.githubusercontent.com/36028424/42077947-40c4e386-7bad-11e8-8a5d-70123bba83d1.png)

Thanks for accepting my proposal..Best regards! 

-Tobaloidee

**Comment by ycuwq** [comment]
Thanks, Merged and looks great.

**Comment by Tobaloidee** [comment]
Hi @ycuwq  you can get all the variants and file formats of the logo on this link:

[Ai-PNG-SVG](https://drive.google.com/drive/folders/1CyXi2-G6Iy84HPmPvtVJIrDC-Xk313BK)

Thanks!

**Comment by ycuwq** [comment]
Ok, I will check it out.
